### ISSUE TITLE
Config file issue

### ISSUE THREAD

**Issue by timchya** [sildur/TGRSBot#2]
Having trouble executing the dlconfig.cfg file. Windows 10 OS python 3.9. I'm a complete beginner at Python but googling the hell out of this issue isn't getting me anywhere, sorry! 

Required modules are all installed AFAIK, some like configparser were already included in the latest version of python i believe. 

Confirmed config file name and path matches below. I edited the bot.py for full OS file path, however this was done after the initial error with the original code. 

Log file output: 

DLCONFIG file: 2021-01-19 18:43:10,612 - root - ERROR - Error reading config file C:\IT\TGRSBot-master\dlconfig.cfg

[COMMON]
bot_token = xxxxxxx:xxxxxxxxxxxx
basic_user = abc
basic_pass = abc123
allowed_chat = -xxxxxxxxxxx
[SONARR]
URL = http://localhost:38082/
TOKEN = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
root_folder_path = \\plex\tv2\

[RADARR]
[URL] = http://127.0.0.1:38083/
TOKEN = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
root_folder_path = \\plex\movies\

**Comment by sildur** [comment]
Hello! Sorry, but this repo was a work in progress. I finally put some time into it, and now it works as expected. Please update your copy and try using the new dlconfig.example as a base. The previous one had some errors.
